### ISSUE TITLE
Invalid memory address or nil pointer dereference - parsing MapzenResponse

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-api#7]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64a344]

goroutine 1 [running]:
github.com/whosonfirst/go-whosonfirst-api/client.(*HTTPClient).ExecuteMethod(0xc420625f20, 0x7fff568b882d, 0x19, 0xc4205729c8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/mapzen/go-whosonfirst-api/src/github.com/whosonfirst/go-whosonfirst-api/client/http.go:96 +0x6d4
github.com/whosonfirst/go-whosonfirst-api/client.(*HTTPClient).ExecuteMethodPaginated(0xc420625f20, 0x7fff568b882d, 0x19, 0xc42000e080, 0xc42015c300, 0xc420108cf0, 0x0)
        /usr/local/mapzen/go-whosonfirst-api/src/github.com/whosonfirst/go-whosonfirst-api/client/http.go:152 +0x81
main.main()
        /usr/local/mapzen/go-whosonfirst-api/cmd/wof-api.go:274 +0x1095
```

Specifically:

```
                if IsMapzenError(status_code) {

                        rsp, err := mapzen.ParseMapzenResponse(http_rsp)

                        if err != nil {
                                msg := fmt.Sprintf("%d %s", rsp.Meta.StatusCode, rsp.Results.Error.Message)
                                return nil, errors.New(msg)

                        }
                }
```

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-api/commit/99813f1d64adb207eeb53bdc206f2d5ac9a72a8a
